Category.create(name: "Purses").image.attach(io: File.open('app/assets/images/purses.jpg'), filename: 'purses.jpg')
Category.create(name: "Wallets").image.attach(io: File.open('app/assets/images/wallets.jpg'), filename: 'wallets.jpg')
Category.create(name: "Bags").image.attach(io: File.open('app/assets/images/bags.jpg'), filename: 'bags.jpg')
Category.create(name: "Sheathes").image.attach(io: File.open('app/assets/images/sheathes.jpg'), filename: 'sheathes.jpg')
Category.create(name: "Belts").image.attach(io: File.open('app/assets/images/belts.jpg'), filename: 'belts.jpg')
Category.create(name: "Other").image.attach(io: File.open('app/assets/images/other.jpg'), filename: 'other.jpg')